codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 50%
        threshold: 1%
        base: auto

ignore:
  - "tests/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
